### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by edlanglois** [so-much-meta/lczero_tools#1]
First of all, thanks for writing this! 
Do you mind adding a license file? I have some modifications that I'd like to submit (or include in my Github fork) and I would be more comfortable if the code had a license. Since you extend code from python-chess the license should probably be GPLv3 or another compatible license.

**Comment by trevor-graffa** [comment]
Done! GPLv3 seems fine to me... My philosophy really is I have no attachment to anything about this code, and I'd prefer to just leave it 100% up to others how they'd like to use it... But agreed, GPLv3 compatible does seem like the right choice (per both leela-chess-zero and python chess integration).
